### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by vicentllongo** [vicentllongo/simplecov-json#14]
I don't really use this gem myself anymore so I can't properly maintain it. Asking here if someone is interested to take the ownership of the GitHub repo and the gem.

**Comment by kevjin** [comment]
Hi @vicentllongo,
I'm Kevin and we use this gem at our company. I actually came across this issue because #12 broke some of our tests, so I have created the following fix PRs: #16, #18.

It's a simple and useful gem, and I would be more than happy to take over maintaining it. I've done some other OSS work in the past, and would be interested in contributing more.

**Comment by marcelotoledo5000** [comment]
Hello guys, I'd like too.

I have also tried to keep this gem in my projects and in my company. I wish I could contribute to her evolution.

**Comment by vicentllongo** [comment]
Hi @kevjin and @marcelotoledo5000. If you are still interested to become a maintainer, send me a DM in Twitter, my handle is "@villosil"
